name: Run userspace unit tests

on:
  push:
    branches: [ "main", "dev", "test" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run aarch64 tests
      working-directory: ./kpi
      run: RUST_BACKTRACE=1 cargo test --verbose --lib --features aarch64_tests

    # Need non-ofw device_probe to enable
    #- name: Run x86_64 tests
    #  working-directory: ./kpi
    #  run: RUST_BACKTRACE=1 cargo test --verbose --lib --features x86_64_tests
